AllCops:
  TargetRubyVersion: 2.4

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - spec/**/*
