sudo: false
language: ruby
rvm:
  - 2.4.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master

bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem install bundler -v 1.16.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  disabled: true
