sudo: false
language: ruby
rvm:
  - 2.4.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem install bundler -v 1.16.0

notifications:
  disabled: true
